sudo: false
language: go

go:
  - tip
  - 1.9
  - 1.8

before_script:
  - go get -u golang.org/x/lint/golint

script:
  - go build ./...
  - golint ./...
  - go test -short -v ./...

after_script:
  - F=$(go fmt ./...); if [ ! -z "$F" ]; then echo "Please gofmt for"$'\n'"$F"; exit 1; fi
